---
# Homebrew setup prerequisites.
- name: Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    state: directory
  become: yes
  when: "ansible_distribution_version is version('10.13', '>=')"

- name: Ensure Homebrew parent directory has correct permissions (MacOS < 10.13).
  file:
    path: "{{ homebrew_prefix }}"
    owner: root
    group: admin
    state: directory
    mode: 0775
  become: yes
  when: "ansible_distribution_version is version('10.13', '<')"
